services:
 py311:
  build:
   context: .
   args:
     PYTHON_VERSION: 3.11-slim
  volumes:
   - .:/app

 py312:
  build:
   context: .
   args:
     PYTHON_VERSION: 3.12-slim
  volumes:
   - .:/app

 py313:
  build:
   context: .
   args:
     PYTHON_VERSION: 3.13-slim
  volumes:
   - .:/app
